edison_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from game.views import index_view

urlpatterns = [
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^game/', include('game.urls', namespace='game')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('game.api.urls', namespace='api')),
    url(r'^$', index_view, name='index_view')
]

game/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^online-users/$', views.OnlineUsersAPIView.as_view(), name='online_users'),
]

game/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^join_game/(?P<pk>\d+)/$', views.join_game, name="join_game"),
    url(r'^create_game/$', views.create_game, name="create_game"),
    url(r'^start_game/$', views.start_game, name='start_game'),
    url(r'^make_party/$', views.make_party, name='make_party'),
    url(r'^leave_game/$', views.leave_game, name='leave_game'),
    url(r'^get_hint/$', views.get_hint, name='get_hint'),
    url(r'^round_timeout/$', views.round_timeout, name='round_timeout'),
]

game/models.py
import json
from django.http import JsonResponse
from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User

from . import constants
# Create your models here.


class BaseModel(models.Model):
    """
    Model for add created/updated fields
    """
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Updated")

    class Meta:
        abstract = True


class GameLobbie(BaseModel):
    """
    GameLobbies model
    """
    GAME_STATUS = (
        (constants.PARTICIPANTS_SET, "Participants set"),
        (constants.READY_FOR_GAME, "Ready for game"),
        (constants.GAME_STARTED, "Game started"),
        (constants.GAME_ENDED, "Game ended")
    )

    status = models.PositiveIntegerField(choices=GAME_STATUS, default=0, verbose_name="Status")
    title = models.CharField(max_length=200, verbose_name="Title")
    party_time = models.PositiveIntegerField(default=5, verbose_name="Party time")
    author = models.ForeignKey(User, related_name="my_lobbies", verbose_name="Author")
    opponent = models.ForeignKey(User, related_name="my_games", verbose_name="Opponent", null=True, blank=True)
    game_winner = models.ForeignKey(User, related_name="won_games", verbose_name="Winner", null=True, blank=True)
    users_hint_used = models.ManyToManyField(User, related_name='used_hints', verbose_name="Hints used",
                                       null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("game:join_game", args=[self.pk])

    def calculate_game_winner(self, r, channel_name, game_round):
        """
        Calculate game winner
        :param r: redis connection object
        :param channel_name: str - channel to publish
        :param game_round: Round - current round
        :return: bool: If game ended - return True
        """
        won_rounds = self.game_rounds.filter(is_tie=False)
        # define game winner
        if won_rounds.count() >= 3:
            if won_rounds.filter(winner=self.author).count() > won_rounds.filter(winner=self.opponent).count():
                winner = self.author.username
                self.game_winner = self.author
                winner_pk = self.author.pk
            else:
                self.game_winner = self.opponent
                winner = self.opponent.username
                winner_pk = self.opponent.pk
            self.status = constants.GAME_ENDED
            self.save()
            r.publish(channel_name, json.dumps({"game_id": self.pk, "game_status": "completed", "winner": winner,
                                                "winner_pk": winner_pk, "is_tie": game_round.is_tie}))
            return True
        return False

    class Meta:
        verbose_name = "Game's lobbie"
        verbose_name_plural = "Game's lobbies"
        ordering = ("created", )


class Round(BaseModel):
    """
    Round models
    """
    game = models.ForeignKey(GameLobbie, related_name="game_rounds", verbose_name="Game lobbie")
    winner = models.ForeignKey(User, verbose_name="won_rounds", null=True, blank=True)
    is_tie = models.BooleanField(default=False, verbose_name="Tie")
    round_number = models.PositiveIntegerField(verbose_name="Round number", default=1)
    user_hint = models.ForeignKey(User, verbose_name="User hint", related_name="round_hints", null=True, blank=True)

    def save(self, *args, **kwargs):
        """
        Overwrite save method to increase round_number
        """
        try:
            last_round = Round.objects.filter(game=self.game).latest('created')
            # if last round not self
            if last_round.pk != self.pk:
                self.round_number = last_round.round_number + 1
        except Round.DoesNotExist:
            pass
        if self.is_tie and self.winner:
            self.winner = None
        super(Round, self).save(*args, **kwargs)

    def __str__(self):
        return "Round {} of {}".format(self.round_number, self.game.title)

    class Meta:
        verbose_name = "Round"
        verbose_name_plural = "Rounds"
        ordering = ("created",)


class Party(BaseModel):
    """
    Party model
    """
    GAME_CHOICES = (
        (constants.ROCK, "rock"),
        (constants.SPOCK, "Spock"),
        (constants.PAPER, "paper"),
        (constants.LIZARD, "lizard"),
        (constants.SCISSORS, "scissors")
    )
    user = models.ForeignKey(User, related_name="parties", verbose_name="User")
    user_choice = models.PositiveIntegerField(choices=GAME_CHOICES, verbose_name="User choice")
    round = models.ForeignKey(Round, related_name="parties", verbose_name="Round")

    def __str__(self):
        return "User {} in game {} round {}".format(self.user.username, self.round.game.title, self.round.round_number)

    class Meta:
        verbose_name = "Party"
        verbose_name_plural = "Parties"
        ordering = ("created", )

game/forms.py
from django import forms

from .models import GameLobbie


class GameLobbieForm(forms.ModelForm):
    """
    Form for create GameLobbie
    """
    class Meta:
        model = GameLobbie
        fields = ("title", "party_time",)

game/api/views.py
import redis

from django.conf import settings

from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response

from account.functions import get_online_users
from .serializers import UserSerializer

r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


class OnlineUsersAPIView(ListAPIView):
    """
    Return online users list
    """
    permission_classes = (IsAuthenticatedOrReadOnly, )

    def get_queryset(self):
        users = get_online_users(r)
        return users

    def list(self, request, *args, **kwargs):
        serializer = UserSerializer(self.get_queryset(), many=True)
        return Response(serializer.data)

game/views.py
import redis
import json
import datetime
import random

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from common.decorators import ajax_required

from . import constants
from .forms import GameLobbieForm
from .models import GameLobbie, Party, Round
from .functions import publish_round_information

r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

# Create your views here.


def index_view(request):
    """
    Show index page. Show games list and online users list.
    :param request: HttpRequest
    :return: HttpResponse
    """
    games = GameLobbie.objects.all()
    return render(request, "game/index.html", {"games": games})


@login_required
def create_game(request):
    """
    Handle create game form. If game created redirect to game.
    :param request: HttpRequest
    :return: HttpResponse
    """
    if request.method == 'POST':
        form = GameLobbieForm(request.POST)
        if form.is_valid():
            new_game = form.save(commit=False)
            new_game.author = request.user
            new_game.save()
            game_round = Round()
            game_round.game = new_game
            game_round.save()
            r.publish('new_games', json.dumps({'title': new_game.title, 'author': new_game.author.username,
                                               'pk': new_game.pk, 'game_status': 'Participants set', 'status': 'new'}))
            return redirect(reverse_lazy('game:join_game', args=[new_game.pk]))
    else:
        form = GameLobbieForm()
    return render(request, "game/create_game.html", {"form": form})


@login_required
def join_game(request, pk):
    """
    Join game.
    :param request: HttpRequest
    :param pk: int: GameLobbie pk
    :return: HttpResponse
    """
    game = get_object_or_404(GameLobbie, pk=pk)
    user_leaved_key = "leaved_" + str(request.user.pk)
    # Check if user leaved previous his game
    record = r.get(user_leaved_key)
    if record:
        leaved_date = datetime.datetime.strptime(str(record, 'utf-8'), "%Y-%m-%d %H:%M")
        delta = datetime.datetime.now() - leaved_date
        if delta.total_seconds() < 60.0:
            messages.info(request, "You should wait 1 minute before join game")
            return redirect(reverse_lazy('index_view'))
        else:
            r.delete(user_leaved_key)
    if (request.user != game.author or request.user != game.opponent) and game.opponent is not None:
            messages.error(request, "All players joined the game")
            return redirect(reverse_lazy('index_view'))
    choices = Party.GAME_CHOICES
    channel = "game_" + str(game.pk)
    r.publish(channel, json.dumps({"game_id": game.pk}))
    if game.status == constants.PARTICIPANTS_SET and not game.opponent:
        if request.user != game.author:
            game.opponent = request.user
            game.status = constants.READY_FOR_GAME
            game.save()
            r.publish(channel, json.dumps({"game_status": "ready", "opponent": request.user.username}))
    else:
        if request.user != game.author and request.user != game.opponent:
            messages.error(request, "You are already joined this game")
            return redirect(reverse_lazy("index_view"))
    game_rounds = game.game_rounds.all()
    last_round = game_rounds.latest('created')
    return render(request, "game/playing_game.html", {"game": game, 'choices': choices, "game_rounds": game_rounds,
                                                      "last_round": last_round})


@login_required
@require_POST
@ajax_required
def start_game(request):
    """
    Change game status to GAME_STARTED
    :param request: HttpRequest (Post, ajax)
    :return: HttpResponse (Json)
    """
    try:
        game = GameLobbie.objects.get(pk=request.POST.get('pk'))
        game.status = constants.GAME_STARTED
        game.save()
        game_round = game.game_rounds.last()
        channel_name = "game_" + str(game.pk)
        r.publish(channel_name, json.dumps({"round": game_round.round_number, "round_id": game_round.pk,
                                            "game_status": "started"}))
        return JsonResponse({"status": "ok", "round": game_round.round_number})
    except GameLobbie.DoesNotExist:
        return JsonResponse({"status": "error", "text": "Game not found"})


@login_required
@require_POST
@ajax_required
def make_party(request):
    """
    Make user party
    :param request: HttpRequest (Post, Ajax)
    :return: HttpResponse (Json)
    """
    game = get_object_or_404(GameLobbie, pk=request.POST.get('pk'))
    game_round = Round.objects.get(pk=request.POST.get("round"))
    if game_round.parties.count() > 2:
        return JsonResponse({"error": "all users make party"})
    if Party.objects.filter(round=game_round, user=request.user).exists():
        return JsonResponse({"error": "you make you party"})
    party = Party()
    party.game = game
    party.user = request.user
    party.user_choice = request.POST.get("choice")
    party.round = game_round
    party.save()
    channel_name = "game_" + str(game.pk)
    r.publish(channel_name, json.dumps({"round_id": game_round.pk, "round_state": "make_party",
                                        "player": request.user.username}))
    # if all users make party calculate winner
    if game_round.parties.count() == 2:
        party_1 = game_round.parties.all()[0]
        party_2 = game_round.parties.all()[1]
        winner = None
        winner_pk = None
        if (party_1.user_choice + 1) % 5 == party_2.user_choice:
            game_round.winner = party_2.user
            winner = party_2.user.username
            winner_pk = party_2.user.pk
        elif (party_1.user_choice + 2) % 5 == party_2.user_choice:
            game_round.winner = party_2.user
            winner = party_2.user.username
            winner_pk = party_2.user.pk
        elif party_1.user_choice == party_2.user_choice:
            game_round.is_tie = True
        else:
            game_round.winner = party_1.user
            winner = party_1.user.username
            winner_pk = party_1.user.pk
        game_round.save()
        if game.calculate_game_winner(r, channel_name, game_round):
            return JsonResponse({"status": "ok", "game status": "completed"})
        publish_round_information(r, channel_name, game_round.game, game_round, False, winner, winner_pk)
    return JsonResponse({"status": "ok", "round": game_round.round_number})


@csrf_exempt
@require_POST
def leave_game(request):
    """
    If user leaves game ake record in redis
    :param request: HttpRequest (Post from tornado)
    :return: HttpResponse
    """
    api_key = request.POST.get("API_KEY")
    if api_key == settings.API_KEY:
        try:
            user = User.objects.get(pk=request.POST["user_pk"])
        except User.DoesNotExist:
            return JsonResponse({"status": "error", "reason": "User not found"})
        try:
            game = GameLobbie.objects.get(pk=request.POST["game_pk"])
        except GameLobbie.DoesNotExist:
            return JsonResponse({"status": "error", "reason": "Game not found"})
        if game.status != constants.GAME_ENDED:
            game.status = constants.GAME_ENDED
            if game.author == user:
                game.game_winner = game.opponent
            else:
                game.game_winner = game.author
            user_leaved_key = "leaved_" + str(user.pk)
            r.set(user_leaved_key, datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))
            game.save()
            return JsonResponse({"status": "ok", "reason":"game ended"})
        return JsonResponse({"status": "ok", "reason": "game ended normaly"})
    else:
        return JsonResponse({"status": "error", "reason": "API KEY incorrect"})


@require_POST
@ajax_required
@login_required
def get_hint(request):
    """
    Return user hint
    :param request: HttpRequest (POST, AJAX)
    :return: HttpResponse (JSON)
    """
    game_round = Round.objects.get(pk=request.POST.get('round'))
    if request.user in game_round.game.users_hint_used.all():
        return JsonResponse({"error": "You used hint"})
    parties = game_round.parties.exclude(user=request.user)
    random_hint = random.choice([constants.ROCK, constants.PAPER, constants.SCISSORS, constants.SPOCK,
                                 constants.LIZARD])
    game_round.game.users_hint_used.add(request.user)
    game_round.user_hint = request.user
    game_round.save()
    if parties.exists():
        party_choice = parties[0].user_choice
        hint = random.choice([party_choice, random_hint])
    else:
        return JsonResponse({"error": "You loose hint"})
    if hint == constants.ROCK:
        hint_str = "rock"
    elif hint == constants.PAPER:
        hint_str = "paper"
    elif hint == constants.SCISSORS:
        hint_str = "scissors"
    elif hint == constants.SPOCK:
        hint_str = "Spock"
    else:
        hint_str = "lizard"
    channel_name = "game_" + str(game_round.game.pk)
    username = request.user.username
    r.publish(channel_name, json.dumps({'message': 'User: {} use hint'.format(username), 'hint': hint_str,
                                        'game_status': 'hint_used'}))
    return JsonResponse({"status": "ok", "hint": hint_str})


@require_POST
@ajax_required
@login_required
def round_timeout(request):
    """
    End round by timeout
    :param request: HttpRequest(POST, AJAX)
    :return: HttpResponse
    """
    game_round = Round.objects.get(pk=request.POST.get('pk'))
    channel_name = "game_" + str(game_round.game.pk)

game/templates/game/create_game.html
{% extends "base.html" %}
{% load game_tags %}
{% block title %}
    Create new game
{% endblock %}
{% block scripts %}
{% endblock %}
{% block page_header %}Create new page{% endblock %}
{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.title.label_tag }}{{ form.title.errors.as_text }}
            {{ form.title|add_class_to_formfield:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.party_time.label_tag }}{{ form.party_time.errors.as_text }}
            {{ form.party_time|add_class_to_formfield:"form-control" }}
        </div>
        <input type="submit" value="Create" class="btn btn-default">
    </form>
{% endblock %}

game/templates/game/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    Rock-paper-scissors-Lizard-Spock game
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/game_refresh.js' %}"></script>
    <script>
        $(document).ready(function () {
            checkNewGames();
        });
    </script>
{% endblock %}
{% block page_header %}Main page{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Games created</h2>
                <table class="table table-responsive" id="tableGames">
                    <thead>
                        <tr>
                            <th>Game title</th>
                            <th>Game author</th>
                            <th>Game status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for game in games %}
                            <tr>
                                <td>{{ game.title }}</td>
                                <td>{{ game.author }}</td>
                                <td>{{ game.get_status_display }}</td>
                                <td>
                                    {% if game.status == PARTICIPANTS_SET %}
                                        <a href="{% url 'game:join_game' game.pk %}">
                                            Join game
                                        </a>
                                    {% elif game.status == GAME_ENDED %}
                                        {% if game.game_winner %}
                                            Winner: {{ game.game_winner.username }}
                                        {% endif %}
                                    {% else %}
                                        Game playing
                                    {% endif %}
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3">
                                    No games created
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <h2>Players online</h2>
                <div id="userlist">
                    {% for user in online_users %}
                        <p id="user{{ user.pk }}">{{ user.username }}</p>
                    {% empty %}
                        No users online
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

game/templates/game/playing_game.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    {{ game.title }}
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/play_game.js' %}"></script>
    <script>
        $(document).ready(function () {
            var myUsername = '{{ request.user.username }}';
            var gameAuthor = '{{ game.author }}';
            var gameCount = '{{ game.party_time }}';
            var gamePk = '{{ game.pk }}';
            var userPk = '{{ request.user.pk }}';
            playGame(myUsername, gameAuthor, gameCount, gamePk, userPk);
        });
    </script>
{% endblock %}
{% block page_header %}{{ game.title }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-9">
            {% if game.status == PARTICIPANTS_SET %}
                <h2 id="game_status">You are waiting opponent</h2>
            {% elif game.status == READY_FOR_GAME %}
                <h2 id="game_status">
                    Your opponent: {% if request.user == game.opponent %}{{ game.author }}{% else %}{{ game.opponent }}{% endif %}
                </h2>
                {% if game.author == request.user %}
                    <a href="#" class="btn btn-success" id="start_game" onclick="StartGame({{ game.pk }}); event.preventDefault();">Start game</a>
                {% endif %}
            {% elif game.status == GAME_STARTED %}
                <h2 id="game_status">
                    Your opponent: {% if request.user == game.opponent %}{{ game.author }}{% else %}{{ game.opponent }}{% endif %}
                </h2>
                <h3 id="roundText">Round #{{ last_round.round_number }}</h3>
            {% endif %}
            <p id="hint"></p>
            <input type="hidden" name="round" id="round" {% if last_round %} value="{{ last_round.pk }}"{% endif %}>
            <div class="form-group">
                <select id="party" class="form-control" {% if game.status < GAME_STARTED %}disabled{% endif %}>
                    {% for choice in choices %}
                        <option value="{{ choice.0 }}" class="form-control">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="makeParty" onclick="makeParty({{ game.pk }}); event.preventDefault();" {% if game.status < GAME_STARTED %}disabled{% endif %}>
                    Send
                </button>
            </div>
            <div class="form-group">
                <button class="btn btn-success" id="getHint" onclick="getHint(); event.preventDefault();" {% if game.status < GAME_STARTED %}disabled{% endif %}>
                    Get hint
                </button>
            </div>
        </div>
        <div class="col-md-3">
            <div id="{{ game.party_time }}" class="counter"></div>
            <div id="log">
                {% for round in game_rounds %}
                    {% if round.parties.exists %}
                        {% for party in round.parties.all %}
                            <h4>User: {{ party.user.username }} </h4>
                            <p>Party: {{ party.get_user_choice_display }}</p>
                        {% endfor %}
                        {% if round.is_tie %}
                            <h5>Round #{{ round.round_number }} is tie</h5>
                        {% else %}
                            <h5>Round #{{ round.round_number }} winner is {{ round.winner.username }}</h5>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}